chore(rust): bump rust nightly (#12077)
# Description of change

A dependency I want to update in another PR complains that it is
incompatible with our rust nightly version. Also the rust nightly
version is older than our current stable toolchain, so I bumped it to
todays nightly version.

```
  error: rustc 1.94.0-nightly is not supported by the following package:
  sysinfo@0.39.5 requires rustc 1.95
```

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration
tests)
- [ ] Patch-specific tests (correctness, functionality coverage)
- [ ] I have added tests that prove my fix is effective or that my
feature works
- [ ] I have checked that new and existing unit tests pass locally with
my changes